version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: es-container
    environment:
      - node.name=es-node
      - cluster.name=es-cluster
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=your_elastic_password
    ports:
      - 9200:9200
      - 9300:9300

  nodejs:
    build: ./backend
    container_name: nodejs-app
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    ports:
      - 3000:3000
    depends_on:
      - elasticsearch

  react-app:
    build: ./frontend
    container_name: react-app
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules  # Prevents overwriting node_modules
    ports:
      - 3500:3500
    command: ["npm", "start"]
    environment:
      - WDS_SOCKET_PORT=3500  # Ensures live reload works in Docker
    stdin_open: true
    tty: true
